### ISSUE TITLE
the original data generation script

### ISSUE THREAD

**Issue by gucasbrg** [Eric991005/Multitask-Stockformer#1]
The folder Stock_CN_2018-03-01_2024-03-01 contains the original data. Could you provide a script that generates the original data? This is to review the details of
section 5.3.1. Factor Value Preprocessing and
section 5.3.2. Neutralization Process. Thank you.

**Comment by sivavishnubramma** [comment]
Would you be able to share the data/evaluation metrics to compare the StockFormer and the Multitask-StockFormer models?

**Comment by Eric991005** [comment]
I have uploaded and organized all the content related to factor processing for your reference. The specific details are available in the folder `data_processing_script/volume_and_price_factor_construction`. Please feel free to review it at your convenience.

**Comment by Eric991005** [comment]
I have uploaded the data, and you can refer to the "Original Dataset and Sub-Datasets After Partition" section in the README file to access it. For the evaluation metrics, you can construct them by following the instructions in section 6.2.2 of the thesis. Please let me know if you need further assistance.

**Comment by Eric991005** [comment]
> Would you be able to share the data/evaluation metrics to compare the StockFormer and the Multitask-StockFormer models?

I have uploaded the data, and you can refer to the "Original Dataset and Sub-Datasets After Partition" section in the README file to access it. For the evaluation metrics, you can construct them by following the instructions in section 6.2.2 of the thesis. Please let me know if you need further assistance.

**Comment by Eric991005** [comment]
> The folder Stock_CN_2018-03-01_2024-03-01 contains the original data. Could you provide a script that generates the original data? This is to review the details of section 5.3.1. Factor Value Preprocessing and section 5.3.2. Neutralization Process. Thank you.

I have uploaded and organized all the content related to factor processing for your reference. The specific details are available in the folder data_processing_script/volume_and_price_factor_construction. Please feel free to review it at your convenience.
